name: Assignment Build And Test

on:
  push:
    branches: [ Assignment* ]
  pull_request:
    branches: [ Assignment* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd
      
    - name: Export Dev Certificates
      run: |
        dir $HOME/.pki/nssdb
        dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
      
    - name: Trust Dev Certificates for Chromium
      run: |
        certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n localhost -i /usr/local/share/ca-certificates/  aspnet/https.crt
        certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localhost -i /usr/local/share/ca-certificates/  aspnet/https.crt

    - name: Run Npm Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: |
        npm install
        npm run build:prod

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Verify Build Badge
      run: |
        echo "This is a test"
        Write-Host "This is another test"
        Get-Item README.md
