# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: DeployFinalAssignment

on:
  push:
    branches: [ Assignment* ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./SecretSanta/src/SecretSanta.Web

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: npm install
      run: npm install
      
    - name: npm build
      run: npm run build:prod

    - name: (WEB) Build with dotnet
      run: dotnet build --configuration Release

    - name: (WEB) dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSanta

    - name: (API) Build with dotnet
      working-directory: ./SecretSanta/src/SecretSanta.Api
      run: dotnet build --configuration Release

    - name: (API) dotnet publish
      working-directory: ./SecretSanta/src/SecretSanta.Api
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/apiSecretSanta

    - name: (API) Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: Cybotive-As6-SecretSantaAPI
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EA128BB4BEBA47A6BDDA3D13595E900E }}
        package: ${{env.DOTNET_ROOT}}/apiSecretSanta

    - name: (WEB) Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: Cybotive-EWU-CSCD379-2021-Spring
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D4A88AAF84D24369A2691A81527B8CEF }}
        package: ${{env.DOTNET_ROOT}}/binSecretSanta

