# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - EWU-CSCD379-2021-Spring(Production), Build and deploy DotnetCore app

on:
  push:
    branches: [ Lecture* ]
  pull_request:
    branches: [ Lecture* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./UserGroup/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd

    - name: npm install
      working-directory: ./UserGroup/src/UserGroup.Web/
      run: npm install
    - name: npm build
      working-directory: ./UserGroup/src/UserGroup.Web/
      run: npm run build:prod

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: dotnet publish
      working-directory: ./UserGroup/src/UserGroup.Web/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binUserGroup

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: EWU-CSCD379-2021-Spring
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_254B5FD2C67B46A7BF65C1045E112A00 }}
        package: ${{env.DOTNET_ROOT}}/binUserGroup

